# Generated by Django 5.2.5 on 2025-08-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
