# Generated by Django 5.2.5 on 2025-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('General Legal Categories', [('Civil Rights', 'Civil Rights'), ('Property & Real Estate', 'Property & Real Estate'), ('Cyber & Digital Law', 'Cyber & Digital Law'), ('Business & Corporate', 'Business & Corporate'), ('Employment & Labour', 'Employment & Labour')]), ('Support', [('Urgent Help', 'Urgent Help'), ('Legal Advice', 'Legal Advice'), ('Case Discussion', 'Case Discussion'), ('Recent Ammendents', 'Recent Ammendents')]), ('Lawgic AI', [('Lawgic Verified', 'Lawgic Verified')])], default='Legal Advice', max_length=22),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
