services:
  - type: web
    name: lawgic-ai
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn lawgic.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lawgic.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DEBUG
        value: "False"
      # Add any other required environment variables like database URLs or API keys here
