services:
  - type: web
    name: lawgic-ai
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python lawgic/manage.py collectstatic --noinput
      python lawgic/manage.py migrate
    startCommand: gunicorn lawgic.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lawgic.settings  
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: ${SECRET_KEY}  
      - key: DEBUG
        value: "False"
